var classfiftyone__devicedetection__onpremise_1_1_device_detection_hash_engine_module_1_1_evidence_device_detection_swig =
[
    [ "__init__", "classfiftyone__devicedetection__onpremise_1_1_device_detection_hash_engine_module_1_1_evidence_device_detection_swig.html#a9acd89e493fa52620d8351c1d5bfade6", null ],
    [ "thisown", "classfiftyone__devicedetection__onpremise_1_1_device_detection_hash_engine_module_1_1_evidence_device_detection_swig.html#aa9bcb4b1a724ea6e20c50ecfa59531a6", null ]
];